select ten from doanh_nghiep where danh_gia_xep_hang > 4.5	yelp
select ten from doanh_nghiep where danh_gia_xep_hang = 3.5	yelp
select id_nguoi_tieu_dung from nguoi_tieu_dung where ten = "michelle"	yelp
select tieu_bang from doanh_nghiep where ten = "whataburger"	yelp
select t1.thanh_pho from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "mgm grand buffet" and t2.ten_loai_hinh = "category category name0"	yelp
select thanh_pho from doanh_nghiep where danh_gia_xep_hang < 1.5	yelp
select thanh_pho from doanh_nghiep where ten = "taj mahal"	yelp
select van_ban from danh_gia where danh_gia_xep_hang < 1	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.danh_gia_xep_hang > 3.5 and t2.ten_loai_hinh = "restaurant"	yelp
select t1.thanh_pho from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "taj mahal" and t2.ten_loai_hinh = "restaurant"	yelp
select t1.van_ban from nguoi_tieu_dung as t2 join danh_gia as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t2.ten = "niloofar"	yelp
select t1.ten from danh_gia as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t3 on t3.id_nguoi_tieu_dung = t2.id_nguoi_tieu_dung where t3.ten = "niloofar"	yelp
select t1.ten from danh_gia as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t3 on t3.id_nguoi_tieu_dung = t2.id_nguoi_tieu_dung where t2.danh_gia_xep_hang = 5 and t3.ten = "niloofar"	yelp
select t4.van_ban from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t4 on t4.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t5 on t5.id_nguoi_tieu_dung = t4.id_nguoi_tieu_dung where t2.ten_loai_hinh = "italian" and t3.ten_loai_hinh = "category category name1" and t5.ten = "michelle"	yelp
select count ( distinct t3.van_ban ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "cafe zinho" and t1.tieu_bang = "texas" and t2.ten_loai_hinh = "restaurant"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.danh_gia_xep_hang = 5 and t2.ten_loai_hinh = "italian" and t3.ten_loai_hinh = "restaurant"	yelp
select t1.ten_khu_pho_lan_can from loai_hinh as t3 join doanh_nghiep as t2 on t3.id_doanh_nghiep = t2.id_doanh_nghiep join loai_hinh as t4 on t4.id_doanh_nghiep = t2.id_doanh_nghiep join khu_vuc_lan_can as t1 on t1.id_doanh_nghiep = t2.id_doanh_nghiep where t2.thanh_pho = "madison" and t3.ten_loai_hinh = "italian" and t4.ten_loai_hinh = "restaurant"	yelp
select t1.ten_khu_pho_lan_can from loai_hinh as t3 join doanh_nghiep as t2 on t3.id_doanh_nghiep = t2.id_doanh_nghiep join loai_hinh as t4 on t4.id_doanh_nghiep = t2.id_doanh_nghiep join khu_vuc_lan_can as t1 on t1.id_doanh_nghiep = t2.id_doanh_nghiep where t2.thanh_pho = "madison" and t2.danh_gia_xep_hang < 2.5 and t3.ten_loai_hinh = "italian" and t4.ten_loai_hinh = "restaurant"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.tieu_bang = "pennsylvania" and t2.ten_loai_hinh = "restaurant"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.tieu_bang = "pennsylvania" and t2.ten_loai_hinh = "restaurant"	yelp
select t3.van_ban from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.so_luong_danh_gia > 100 and t2.ten_loai_hinh = "pet groomers"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "los angeles" and t2.ten_loai_hinh = "breweries"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "los angeles" and t2.ten_loai_hinh = "breweries"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "los angeles" and t2.ten_loai_hinh = "breweries"	yelp
select t4.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t1.ten = "mesa grill" and t2.ten_loai_hinh = "restaurant"	yelp
select dia_chi_day_du from doanh_nghiep where thanh_pho = "los angeles" and ten = "walmart"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t1.thanh_pho = "dallas" and t2.ten_loai_hinh = "restaurant" and t4.ten = "patrick"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t1.thanh_pho = "dallas" and t2.ten_loai_hinh = "restaurant" and t4.ten = "patrick"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t2.ten_loai_hinh = "bars" and t4.ten = "patrick"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t1.danh_gia_xep_hang >= 3 and t2.ten_loai_hinh = "bars" and t4.ten = "patrick"	yelp
select t3.ten from khoan_tien_boa as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t3 on t3.id_nguoi_tieu_dung = t2.id_nguoi_tieu_dung where t1.ten = "barrio cafe" and t2.nam = 2015	yelp
select ten from doanh_nghiep where danh_gia_xep_hang < 2 and tieu_bang = "texas"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "los angeles" and t2.ten_loai_hinh = "seafood" and t3.ten_loai_hinh = "restaurant"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "los angeles" and t2.ten_loai_hinh = "seafood" and t3.ten_loai_hinh = "restaurant"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "los angeles" and t2.ten_loai_hinh = "seafood" and t3.ten_loai_hinh = "restaurant"	yelp
select t1.van_ban from nguoi_tieu_dung as t2 join danh_gia as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t1.danh_gia_xep_hang > 4 and t2.ten = "patrick"	yelp
select id_doanh_nghiep from doanh_nghiep where thanh_pho = "los angeles" and ten = "apple store"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "dallas" and t1.danh_gia_xep_hang > 4.5 and t2.ten_loai_hinh = "restaurant"	yelp
select t1.ten_khu_pho_lan_can from loai_hinh as t3 join doanh_nghiep as t2 on t3.id_doanh_nghiep = t2.id_doanh_nghiep join khu_vuc_lan_can as t1 on t1.id_doanh_nghiep = t2.id_doanh_nghiep where t2.ten = "flat top grill" and t3.ten_loai_hinh = "category category name0"	yelp
select t2.van_ban from khoan_tien_boa as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "vintner grill" and t2.so_luot_thich > 9	yelp
select t2.van_ban from danh_gia as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "kabob palace" and t2.nam = 2014	yelp
select t3.ten from khoan_tien_boa as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t3 on t3.id_nguoi_tieu_dung = t2.id_nguoi_tieu_dung where t1.thanh_pho = "dallas"	yelp
select t1.thanh_pho from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "mgm grand buffet" and t1.tieu_bang = "texas" and t2.ten_loai_hinh = "restaurant"	yelp
select t4.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join khoan_tien_boa as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t2.ten_loai_hinh = "pet groomers"	yelp
select t2.van_ban from khoan_tien_boa as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "cafe zinho" and t1.tieu_bang = "texas"	yelp
select t4.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t2.ten_loai_hinh = "restaurant"	yelp
select t2.van_ban from khoan_tien_boa as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "cafe zinho" and t1.tieu_bang = "pennsylvania" and t2.nam = 2010	yelp
select t4.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t2.ten_loai_hinh = "restaurant" and t3.nam = 2010	yelp
select t2.van_ban from nguoi_tieu_dung as t3 join danh_gia as t1 on t3.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung join khoan_tien_boa as t2 on t3.id_nguoi_tieu_dung = t2.id_nguoi_tieu_dung where t1.nam = 2012	yelp
select t2.van_ban from danh_gia as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.danh_gia_xep_hang = 2.5	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "madison" and t2.ten_loai_hinh = "escape games"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "madison" and t2.ten_loai_hinh = "escape games"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "madison" and t2.ten_loai_hinh = "escape games"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "madison" and t2.ten_loai_hinh = "escape games"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "madison" and t2.ten_loai_hinh = "escape games"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.danh_gia_xep_hang > 3.5 and t2.ten_loai_hinh = "restaurant"	yelp
select sum ( t4.so_luong ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join luot_dang_ky as t4 on t4.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "los angeles" and t2.ten_loai_hinh = "restaurant" and t3.ten_loai_hinh = "moroccan"	yelp
select sum ( t4.so_luong ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join luot_dang_ky as t4 on t4.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "los angeles" and t2.ten_loai_hinh = "moroccan" and t3.ten_loai_hinh = "restaurant" and t4.ngay = "friday"	yelp
select t4.ngay , sum ( t4.so_luong ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join luot_dang_ky as t4 on t4.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "los angeles" and t2.ten_loai_hinh = "moroccan" and t3.ten_loai_hinh = "restaurant" group by t4.ngay	yelp
select t1.tieu_bang , sum ( t4.so_luong ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join luot_dang_ky as t4 on t4.id_doanh_nghiep = t1.id_doanh_nghiep where t2.ten_loai_hinh = "italian" and t3.ten_loai_hinh = "delis" and t4.ngay = "sunday" group by t1.tieu_bang	yelp
select count ( distinct t1.van_ban ) from nguoi_tieu_dung as t2 join danh_gia as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t1.nam = 2015 and t2.ten = "niloofar"	yelp
select avg ( t1.danh_gia_xep_hang ) from nguoi_tieu_dung as t2 join danh_gia as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t2.ten = "michelle"	yelp
select t2.so_luong from luot_dang_ky as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "cafe zinho" and t2.ngay = "friday"	yelp
select count ( distinct t3.ten ) from danh_gia as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t3 on t3.id_nguoi_tieu_dung = t2.id_nguoi_tieu_dung where t1.thanh_pho = "pittsburgh" and t1.ten = "sushi too"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "pittsburgh" and t1.danh_gia_xep_hang = 4.5 and t2.ten_loai_hinh = "restaurant"	yelp
select count ( distinct van_ban ) from khoan_tien_boa where nam = 2015	yelp
select sum ( t1.so_luot_thich ) from nguoi_tieu_dung as t2 join khoan_tien_boa as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t2.ten = "niloofar"	yelp
select sum ( t2.so_luot_thich ) from khoan_tien_boa as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "cafe zinho"	yelp
select sum ( t2.so_luot_thich ) from khoan_tien_boa as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t3 on t3.id_nguoi_tieu_dung = t2.id_nguoi_tieu_dung where t1.ten = "cafe zinho" and t3.ten = "niloofar"	yelp
select count ( distinct t1.van_ban ) from nguoi_tieu_dung as t2 join khoan_tien_boa as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t1.nam = 2010 and t2.ten = "michelle"	yelp
select count ( distinct t1.van_ban ) from nguoi_tieu_dung as t2 join khoan_tien_boa as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t1.nam = 2010 and t2.ten = "michelle"	yelp
select count ( distinct t1.van_ban ) from nguoi_tieu_dung as t2 join khoan_tien_boa as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t1.thang = "april" and t2.ten = "michelle"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.tieu_bang = "texas" and t2.ten_loai_hinh = "restaurant"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "dallas" and t1.danh_gia_xep_hang > 3.5 and t2.ten_loai_hinh = "bars"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "dallas" and t1.danh_gia_xep_hang > 3.5 and t2.ten_loai_hinh = "bars"	yelp
select count ( distinct t4.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t1.thanh_pho = "dallas" and t1.ten = "texas de brazil" and t1.tieu_bang = "texas" and t2.ten_loai_hinh = "restaurant"	yelp
select count ( distinct t3.ten ) from danh_gia as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t3 on t3.id_nguoi_tieu_dung = t2.id_nguoi_tieu_dung where t1.ten = "bistro di napoli" and t2.nam = 2015	yelp
select count ( distinct t1.ten ) from loai_hinh as t3 join doanh_nghiep as t1 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join khu_vuc_lan_can as t2 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "dallas" and t3.ten_loai_hinh = "restaurant" and t2.ten_khu_pho_lan_can = "hazelwood"	yelp
select count ( distinct id_doanh_nghiep ) from doanh_nghiep where thanh_pho = "dallas" and ten = "starbucks" and tieu_bang = "texas"	yelp
select so_luong_danh_gia from doanh_nghiep where ten = "acacia cafe"	yelp
select avg ( t3.so_luong ) , t3.ngay from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join luot_dang_ky as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.ten = "barrio cafe" and t2.ten_loai_hinh = "restaurant" group by t3.ngay	yelp
select count ( distinct t1.ten ) from khu_vuc_lan_can as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "madison" and t2.ten_khu_pho_lan_can = "stone meadows"	yelp
select count ( distinct t1.van_ban ) from nguoi_tieu_dung as t2 join danh_gia as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t2.ten = "adrienne"	yelp
select count ( distinct t1.van_ban ) from nguoi_tieu_dung as t2 join danh_gia as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t1.thang = "march" and t1.nam = 2014 and t2.ten = "michelle"	yelp
select count ( distinct t1.ten ) from danh_gia as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t3 on t3.id_nguoi_tieu_dung = t2.id_nguoi_tieu_dung where t2.nam = 2010 and t3.ten = "michelle"	yelp
select count ( distinct t1.ten ) from danh_gia as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t3 on t3.id_nguoi_tieu_dung = t2.id_nguoi_tieu_dung where t1.thanh_pho = "san diego" and t2.nam = 2010 and t3.ten = "christine"	yelp
select count ( distinct id_doanh_nghiep ) from doanh_nghiep where thanh_pho = "los angeles" and ten = "target"	yelp
select count ( distinct t4.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t1.thanh_pho = "dallas" and t2.ten_loai_hinh = "irish pub"	yelp
select avg ( danh_gia_xep_hang ) from danh_gia where nam = 2014	yelp
select count ( distinct t4.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join nguoi_tieu_dung as t4 on t4.id_nguoi_tieu_dung = t3.id_nguoi_tieu_dung where t1.ten = "vintner grill" and t2.ten_loai_hinh = "category category name0" and t3.nam = 2010	yelp
select count ( distinct t3.van_ban ) from khu_vuc_lan_can as t1 join doanh_nghiep as t2 on t1.id_doanh_nghiep = t2.id_doanh_nghiep join danh_gia as t3 on t3.id_doanh_nghiep = t2.id_doanh_nghiep where t1.ten_khu_pho_lan_can = "south summerlin"	yelp
select count ( distinct ten ) from nguoi_tieu_dung where ten = "michelle"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t2.ten_loai_hinh = "restaurant"	yelp
select count ( distinct thanh_pho ) from doanh_nghiep where ten = "panda express"	yelp
select count ( distinct t1.van_ban ) from nguoi_tieu_dung as t2 join khoan_tien_boa as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung where t2.ten = "michelle"	yelp
select sum ( t3.so_luong ) from luot_dang_ky as t3 join doanh_nghiep as t1 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join khu_vuc_lan_can as t2 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t2.ten_khu_pho_lan_can = "brighton heights"	yelp
select count ( distinct van_ban ) from danh_gia where thang = "march"	yelp
select count ( distinct van_ban ) , thang from khoan_tien_boa group by thang	yelp
select count ( distinct t1.ten_khu_pho_lan_can ) from khu_vuc_lan_can as t1 join doanh_nghiep as t2 on t1.id_doanh_nghiep = t2.id_doanh_nghiep where t2.thanh_pho = "madison" and t2.danh_gia_xep_hang = 5	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.tieu_bang = "texas" and t2.ten_loai_hinh = "moroccan" and t3.ten_loai_hinh = "restaurant"	yelp
select t1.ten from luot_dang_ky as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep group by t1.ten order by sum ( t2.so_luong ) desc limit 1	yelp
select t1.ten_khu_pho_lan_can from khu_vuc_lan_can as t1 join doanh_nghiep as t2 on t1.id_doanh_nghiep = t2.id_doanh_nghiep where t2.thanh_pho = "madison" group by t1.ten_khu_pho_lan_can order by count ( distinct t2.ten ) desc limit 1	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "dallas" and t1.danh_gia_xep_hang > 3.5 and t2.ten_loai_hinh = "mexican" and t3.ten_loai_hinh = "restaurant"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "dallas" and t1.danh_gia_xep_hang > 3.5 and t2.ten_loai_hinh = "mexican" and t3.ten_loai_hinh = "restaurant"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "dallas" and t1.tieu_bang = "texas" and t2.ten_loai_hinh = "valet service" and t3.ten_loai_hinh = "restaurant"	yelp
select t1.ten from loai_hinh as t3 join doanh_nghiep as t1 on t3.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t4 on t4.id_doanh_nghiep = t1.id_doanh_nghiep join khu_vuc_lan_can as t2 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "madison" and t3.ten_loai_hinh = "italian" and t4.ten_loai_hinh = "restaurant" and t2.ten_khu_pho_lan_can = "meadowood"	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "los angeles" and t1.danh_gia_xep_hang > 3 and t1.so_luong_danh_gia > 30 and t2.ten_loai_hinh = "bars"	yelp
select count ( distinct t1.ten ) from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep join loai_hinh as t3 on t3.id_doanh_nghiep = t1.id_doanh_nghiep where t1.thanh_pho = "edinburgh" and t2.ten_loai_hinh = "restaurant" and t3.ten_loai_hinh = "egyptian"	yelp
select t2.ten from nguoi_tieu_dung as t2 join danh_gia as t1 on t2.id_nguoi_tieu_dung = t1.id_nguoi_tieu_dung group by t2.ten having avg ( t1.danh_gia_xep_hang ) < 3	yelp
select t1.ten from danh_gia as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep where t2.thang = "april" group by t1.ten order by count ( distinct t2.van_ban ) desc limit 1	yelp
select t1.ten from loai_hinh as t2 join doanh_nghiep as t1 on t2.id_doanh_nghiep = t1.id_doanh_nghiep group by t1.ten order by count ( distinct t2.ten_loai_hinh ) desc limit 1	yelp
