SELECT ten FROM doanh_nghiep WHERE danh_gia_xep_hang > 4.5
SELECT ten FROM doanh_nghiep WHERE danh_gia_xep_hang = 3.5
SELECT id_nguoi_tieu_dung FROM nguoi_tieu_dung WHERE ten = 'Michelle'
SELECT thanh_pho FROM doanh_nghiep WHERE ten = 'Whataburger'
SELECT thanh_pho FROM doanh_nghiep WHERE ten = 'tiệc đứng sang trọng MGM'
SELECT thanh_pho FROM doanh_nghiep WHERE danh_gia_xep_hang < 1.5
SELECT thanh_pho FROM doanh_nghiep WHERE ten = 'Taj Mahal'
SELECT van_ban FROM danh_gia WHERE danh_gia_xep_hang < 1
SELECT ten FROM doanh_nghiep WHERE danh_gia_xep_hang > 3.5
SELECT thanh_pho FROM doanh_nghiep WHERE ten = 'Taj Mahal'
SELECT danh_gia.van_ban FROM danh_gia JOIN nguoi_tieu_dung ON danh_gia.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE nguoi_tieu_dung.ten = 'Niloofar'
SELECT doanh_nghiep.ten FROM doanh_nghiep JOIN danh_gia ON doanh_nghiep.id_doanh_nghiep = danh_gia.id_doanh_nghiep JOIN nguoi_tieu_dung ON danh_gia.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE nguoi_tieu_dung.ten = 'Niloofar'
SELECT doanh_nghiep.ten FROM doanh_nghiep JOIN danh_gia ON doanh_nghiep.id_doanh_nghiep = danh_gia.id_doanh_nghiep JOIN nguoi_tieu_dung ON danh_gia.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE nguoi_tieu_dung.ten = 'Niloofar' AND danh_gia.danh_gia_xep_hang = 5
SELECT T1.van_ban FROM danh_gia AS T1 JOIN nguoi_tieu_dung AS T2 ON T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung JOIN doanh_nghiep AS T3 ON T1.id_doanh_nghiep = T3.id_doanh_nghiep JOIN loai_hinh AS T4 ON T3.id_doanh_nghiep = T4.id_doanh_nghiep WHERE T2.ten = 'Michelle' AND T4.ten_loai_hinh = 'nhà hàng Ý'
SELECT COUNT(*) FROM danh_gia JOIN doanh_nghiep ON danh_gia.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Cafe Zinho' AND doanh_nghiep.thanh_pho = 'Texas'
SELECT T1.ten FROM doanh_nghiep AS T1 JOIN loai_hinh AS T2 ON T1.id_doanh_nghiep::text = T2.id_doanh_nghiep WHERE T2.ten_loai_hinh = 'Ý' AND T1.danh_gia_xep_hang = 5
SELECT T1.ten_khu_pho_lan_can FROM khu_vuc_lan_can AS T1 JOIN doanh_nghiep AS T2 ON T1.id_doanh_nghiep = T2.id_doanh_nghiep JOIN loai_hinh AS T3 ON T2.id_doanh_nghiep::text = T3.id_doanh_nghiep WHERE T3.ten_loai_hinh = 'nhà hàng Ý' AND T2.thanh_pho = 'Madison'
SELECT T1.ten_khu_pho_lan_can FROM khu_vuc_lan_can AS T1 JOIN doanh_nghiep AS T2 ON T1.id_doanh_nghiep = T2.id_doanh_nghiep JOIN loai_hinh AS T3 ON T2.id_doanh_nghiep = T3.id_doanh_nghiep JOIN danh_gia AS T4 ON T2.id_doanh_nghiep = T4.id_doanh_nghiep WHERE T3.ten_loai_hinh = 'nhà hàng Ý' AND T4.danh_gia_xep_hang < 2.5
SELECT doanh_nghiep.id_doanh_nghiep, doanh_nghiep.ten, doanh_nghiep.dia_chi_day_du, doanh_nghiep.thanh_pho, doanh_nghiep.vi_do, doanh_nghiep.kinh_do, doanh_nghiep.so_luong_danh_gia, doanh_nghiep.co_mo_cua_hay_khong, doanh_nghiep.danh_gia_xep_hang, doanh_nghiep.tieu_bang FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'nhà hàng' AND doanh_nghiep.thanh_pho = 'Pennsylvania'
SELECT doanh_nghiep.id_doanh_nghiep, doanh_nghiep.ten, doanh_nghiep.dia_chi_day_du, doanh_nghiep.thanh_pho, doanh_nghiep.vi_do, doanh_nghiep.kinh_do, doanh_nghiep.so_luong_danh_gia, doanh_nghiep.co_mo_cua_hay_khong, doanh_nghiep.danh_gia_xep_hang, doanh_nghiep.tieu_bang FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'nhà hàng' AND doanh_nghiep.thanh_pho = 'Pennsylvania'
SELECT danh_gia.van_ban FROM danh_gia JOIN loai_hinh ON danh_gia.id_doanh_nghiep = loai_hinh.id_doanh_nghiep JOIN doanh_nghiep ON danh_gia.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'chải chuốt cho vật nuôi' AND doanh_nghiep.so_luong_danh_gia > 100
SELECT ten FROM doanh_nghiep WHERE thanh_pho = 'Los Angeles'
SELECT * FROM doanh_nghiep WHERE thanh_pho = 'Los Angeles'
SELECT ten, dia_chi_day_du, thanh_pho, vi_do, kinh_do, so_luong_danh_gia, co_mo_cua_hay_khong, danh_gia_xep_hang, tieu_bang FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'Brewery' AND doanh_nghiep.thanh_pho = 'Los Angeles'
SELECT T1.ten FROM nguoi_tieu_dung AS T1 JOIN danh_gia AS T2 ON T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung JOIN doanh_nghiep AS T3 ON CAST(T2.id_doanh_nghiep AS NUMBER) = T3.id_doanh_nghiep WHERE T3.ten = 'Mesa Grill'
SELECT dia_chi_day_du FROM doanh_nghiep WHERE ten = 'Walmart' AND thanh_pho = 'Los Angeles'
SELECT T1.id_doanh_nghiep, T1.ten, T1.dia_chi_day_du, T1.thanh_pho, T1.vi_do, T1.kinh_do, T1.so_luong_danh_gia, T1.co_mo_cua_hay_khong, T1.danh_gia_xep_hang, T1.tieu_bang FROM doanh_nghiep AS T1 JOIN danh_gia AS T2 ON T1.id_doanh_nghiep = T2.id_doanh_nghiep JOIN nguoi_tieu_dung AS T3 ON T2.id_nguoi_tieu_dung = T3.id_nguoi_tieu_dung WHERE T1.thanh_pho = 'Dallas' AND T3.ten = 'Patrick'
SELECT T1.ten FROM doanh_nghiep AS T1 JOIN danh_gia AS T2 ON T1.id_doanh_nghiep = T2.id_doanh_nghiep JOIN nguoi_tieu_dung AS T3 ON T2.id_nguoi_tieu_dung = T3.id_nguoi_tieu_dung WHERE T1.thanh_pho = 'Dallas' AND T3.ten = 'Patrick'
SELECT doanh_nghiep.id_doanh_nghiep, doanh_nghiep.ten, doanh_nghiep.dia_chi_day_du, doanh_nghiep.thanh_pho, doanh_nghiep.vi_do, doanh_nghiep.kinh_do, doanh_nghiep.so_luong_danh_gia, doanh_nghiep.co_mo_cua_hay_khong, doanh_nghiep.danh_gia_xep_hang, doanh_nghiep.tieu_bang FROM doanh_nghiep JOIN danh_gia ON doanh_nghiep.id_doanh_nghiep = danh_gia.id_doanh_nghiep JOIN nguoi_tieu_dung ON danh_gia.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE nguoi_tieu_dung.ten = 'Patrick'
SELECT T3.ten FROM danh_gia AS T1 JOIN nguoi_tieu_dung AS T2 ON T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung JOIN doanh_nghiep AS T3 ON T1.id_doanh_nghiep = T3.id_doanh_nghiep WHERE T2.ten = 'Patrick' AND T1.danh_gia_xep_hang >= 3
SELECT T1.ten FROM nguoi_tieu_dung AS T1 JOIN khoan_tien_boa AS T2 ON T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung JOIN doanh_nghiep AS T3 ON CAST(T2.id_doanh_nghiep AS NUMBER) = T3.id_doanh_nghiep WHERE T3.ten = 'Barrio Café' AND T2.nam = 2015
SELECT * FROM doanh_nghiep WHERE thanh_pho = 'Texas' AND danh_gia_xep_hang < 2
SELECT ten FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'hải sản' AND doanh_nghiep.thanh_pho = 'Los Angeles'
SELECT doanh_nghiep.id_doanh_nghiep , doanh_nghiep.ten , doanh_nghiep.dia_chi_day_du , doanh_nghiep.thanh_pho , doanh_nghiep.vi_do , doanh_nghiep.kinh_do , doanh_nghiep.so_luong_danh_gia , doanh_nghiep.co_mo_cua_hay_khong , doanh_nghiep.danh_gia_xep_hang , doanh_nghiep.tieu_bang FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'hải sản' AND doanh_nghiep.thanh_pho = 'Los Angeles'
SELECT doanh_nghiep.id_doanh_nghiep, doanh_nghiep.ten, doanh_nghiep.dia_chi_day_du, doanh_nghiep.thanh_pho, doanh_nghiep.vi_do, doanh_nghiep.kinh_do, doanh_nghiep.so_luong_danh_gia, doanh_nghiep.co_mo_cua_hay_khong, doanh_nghiep.danh_gia_xep_hang, doanh_nghiep.tieu_bang FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'Hải sản' AND doanh_nghiep.thanh_pho = 'Los Angeles'
SELECT danh_gia.van_ban FROM danh_gia JOIN nguoi_tieu_dung ON danh_gia.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE danh_gia.danh_gia_xep_hang > 4 AND nguoi_tieu_dung.ten = 'Patrick'
SELECT ten, thanh_pho FROM doanh_nghiep WHERE ten = 'Apple' AND thanh_pho = 'Los Angeles'
SELECT doanh_nghiep.id_doanh_nghiep , doanh_nghiep.ten , doanh_nghiep.dia_chi_day_du , doanh_nghiep.thanh_pho , doanh_nghiep.vi_do , doanh_nghiep.kinh_do , doanh_nghiep.so_luong_danh_gia , doanh_nghiep.co_mo_cua_hay_khong , doanh_nghiep.danh_gia_xep_hang , doanh_nghiep.tieu_bang FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'nhà hàng' AND doanh_nghiep.thanh_pho = 'Dallas' AND doanh_nghiep.danh_gia_xep_hang > 4.5
SELECT khu_vuc_lan_can.ten_khu_pho_lan_can FROM doanh_nghiep JOIN khu_vuc_lan_can ON doanh_nghiep.id_doanh_nghiep = khu_vuc_lan_can.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Flat Top Grill'
SELECT khoan_tien_boa.van_ban FROM khoan_tien_boa JOIN doanh_nghiep ON khoan_tien_boa.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Vintner Grill' AND khoan_tien_boa.so_luot_thich > 9
SELECT T1.van_ban FROM danh_gia AS T1 JOIN doanh_nghiep AS T2 ON T1.id_doanh_nghiep = T2.id_doanh_nghiep WHERE T2.ten = 'cung điện Kabob' AND T1.nam = 2014
SELECT DISTINCT nguoi_tieu_dung.ten FROM khoan_tien_boa JOIN doanh_nghiep ON khoan_tien_boa.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep JOIN nguoi_tieu_dung ON khoan_tien_boa.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE doanh_nghiep.thanh_pho = 'Dallas'
SELECT thanh_pho FROM doanh_nghiep WHERE ten = 'tiệc đứng sang trọng MGM' AND thanh_pho LIKE '%TX'
SELECT nguoi_tieu_dung.ten FROM khoan_tien_boa JOIN nguoi_tieu_dung ON khoan_tien_boa.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung JOIN loai_hinh ON khoan_tien_boa.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'chải chuốt cho thú nuôi'
SELECT khoan_tien_boa.van_ban FROM khoan_tien_boa JOIN doanh_nghiep ON khoan_tien_boa.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Cafe Zinho' AND doanh_nghiep.thanh_pho = 'Texas'
SELECT T1.ten FROM nguoi_tieu_dung AS T1 JOIN danh_gia AS T2 ON T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung JOIN doanh_nghiep AS T3 ON T2.id_doanh_nghiep = T3.id_doanh_nghiep JOIN loai_hinh AS T4 ON T3.id_doanh_nghiep = T4.id_doanh_nghiep WHERE T4.ten_loai_hinh = 'nhà hàng'
SELECT khoan_tien_boa.van_ban FROM khoan_tien_boa JOIN doanh_nghiep ON khoan_tien_boa.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'cafe zinho' AND doanh_nghiep.thanh_pho = 'pennsylvania' AND khoan_tien_boa.nam = 2010
SELECT T1.ten FROM nguoi_tieu_dung AS T1 JOIN danh_gia AS T2 ON T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung WHERE T2.nam = 2010
SELECT T1.van_ban FROM danh_gia AS T1 JOIN khoan_tien_boa AS T2 ON T1.id_doanh_nghiep = T2.id_doanh_nghiep AND T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung WHERE T2.nam = 2012
SELECT van_ban FROM danh_gia WHERE danh_gia_xep_hang = 2.5
SELECT COUNT(*) FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE doanh_nghiep.thanh_pho = 'Madison' AND loai_hinh.ten_loai_hinh = 'trò chơi trốn thoát'
SELECT COUNT(*) FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE doanh_nghiep.thanh_pho = 'Madison' AND loai_hinh.ten_loai_hinh = 'trò chơi trốn thoát'
SELECT COUNT(*) FROM doanh_nghiep JOIN loai_hinh ON CAST(doanh_nghiep.id_doanh_nghiep AS TEXT) = loai_hinh.id_doanh_nghiep WHERE doanh_nghiep.thanh_pho = 'Madison' AND loai_hinh.ten_loai_hinh = 'trò chơi trốn thoát'
SELECT COUNT(*) FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = CAST(loai_hinh.id_doanh_nghiep AS NUMBER) WHERE loai_hinh.ten_loai_hinh = 'trò chơi trốn thoát' AND doanh_nghiep.thanh_pho = 'Madison'
SELECT COUNT(*) FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE doanh_nghiep.thanh_pho = 'Madison' AND loai_hinh.ten_loai_hinh = 'trò chơi trốn thoát'
SELECT COUNT(*) FROM doanh_nghiep WHERE danh_gia_xep_hang > 3.5
SELECT SUM(luot_dang_ky.so_luong) FROM luot_dang_ky JOIN doanh_nghiep ON luot_dang_ky.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE doanh_nghiep.thanh_pho = 'Los Angeles' AND loai_hinh.ten_loai_hinh = 'Ma-rốc'
SELECT SUM(luot_dang_ky.so_luong) FROM luot_dang_ky JOIN doanh_nghiep ON luot_dang_ky.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep JOIN loai_hinh ON loai_hinh.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.thanh_pho = 'Los Angeles' AND loai_hinh.ten_loai_hinh = 'Ma-rốc' AND ngay LIKE '%Fri%'
SELECT luot_dang_ky.ngay , SUM(luot_dang_ky.so_luong) FROM luot_dang_ky JOIN doanh_nghiep ON luot_dang_ky.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'Ma-rốc' AND doanh_nghiep.thanh_pho = 'Los Angeles' GROUP BY luot_dang_ky.ngay
SELECT doanh_nghiep.tieu_bang , SUM(luot_dang_ky.so_luong) FROM doanh_nghiep JOIN luot_dang_ky ON doanh_nghiep.id_doanh_nghiep = luot_dang_ky.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Italian Delis' AND ngay LIKE '%Sunday%' GROUP BY doanh_nghiep.tieu_bang
SELECT COUNT(*) FROM danh_gia JOIN nguoi_tieu_dung ON danh_gia.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE nguoi_tieu_dung.ten = 'Niloofar' AND danh_gia.nam = 2015
SELECT AVG(T1.danh_gia_xep_hang) FROM danh_gia AS T1 JOIN nguoi_tieu_dung AS T2 ON T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung WHERE T2.ten = 'Michelle'
SELECT SUM(luot_dang_ky.so_luong) FROM luot_dang_ky JOIN doanh_nghiep ON luot_dang_ky.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Cafe Zinho' AND luot_dang_ky.ngay = 'thứ sáu'
SELECT COUNT(DISTINCT danh_gia.id_nguoi_tieu_dung) FROM danh_gia JOIN doanh_nghiep ON danh_gia.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Sushi Too' AND doanh_nghiep.thanh_pho = 'Pittsburgh'
SELECT COUNT(*) FROM dbo.doanh_nghiep WHERE thanh_pho = 'Pittsburgh' AND danh_gia_xep_hang > 4.5
SELECT COUNT(*) FROM danh_gia JOIN khoan_tien_boa ON danh_gia.id_nguoi_tieu_dung = khoan_tien_boa.id_nguoi_tieu_dung WHERE khoan_tien_boa.nam = 2015
SELECT SUM(so_luot_thich) FROM khoan_tien_boa WHERE id_doanh_nghiep = 'Niloofar'
SELECT SUM(khoan_tien_boa.so_luot_thich) FROM khoan_tien_boa JOIN doanh_nghiep ON khoan_tien_boa.id_doanh_nghiep = CAST(doanh_nghiep.id_doanh_nghiep AS TEXT) WHERE doanh_nghiep.ten = 'Cafe Zinho'
SELECT SUM(khoan_tien_boa.so_luot_thich) FROM khoan_tien_boa JOIN doanh_nghiep ON khoan_tien_boa.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Cafe Zinho'
SELECT COUNT(*) FROM danh_gia AS T1 JOIN nguoi_tieu_dung AS T2 ON T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung WHERE T2.ten = 'Michelle' AND T1.nam = 2010
SELECT COUNT(*) FROM danh_gia T1 JOIN khoan_tien_boa T2 ON T1.id_doanh_nghiep = T2.id_doanh_nghiep JOIN nguoi_tieu_dung T3 ON T1.id_nguoi_tieu_dung = T3.id_nguoi_tieu_dung WHERE T3.ten = 'Michelle' AND T2.nam = 2010
SELECT COUNT(*) FROM nguoi_tieu_dung AS T1 JOIN khoan_tien_boa AS T2 ON T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung WHERE T1.ten = 'Michelle' AND T2.thang = 'tư'
SELECT COUNT(*) FROM doanh_nghiep WHERE thanh_pho = 'Texas'
SELECT COUNT(*) FROM doanh_nghiep WHERE thanh_pho = 'Dallas' AND danh_gia_xep_hang > 3.5
SELECT COUNT(*) FROM doanh_nghiep JOIN loai_hinh ON CAST(doanh_nghiep.id_doanh_nghiep AS TEXT) = loai_hinh.id_doanh_nghiep WHERE doanh_nghiep.thanh_pho = 'Dallas' AND loai_hinh.ten_loai_hinh = 'quán bar' AND doanh_nghiep.danh_gia_xep_hang > 3.5
SELECT COUNT(DISTINCT danh_gia.id_nguoi_tieu_dung) FROM danh_gia JOIN doanh_nghiep ON danh_gia.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Texas de Brazil' AND doanh_nghiep.thanh_pho = 'Dallas'
SELECT COUNT(*) FROM danh_gia JOIN doanh_nghiep ON danh_gia.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Bistro Di Napoli' AND danh_gia.nam = 2015
SELECT COUNT(*) FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'nhà hàng' AND doanh_nghiep.thanh_pho = 'Dallas' AND doanh_nghiep.dia_chi_day_du LIKE '%Hazelwood%'
SELECT COUNT(*) FROM doanh_nghiep WHERE ten = 'Starbucks' AND thanh_pho = 'Dallas'
SELECT COUNT(*) FROM danh_gia JOIN doanh_nghiep ON danh_gia.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Acacia Cafe'
SELECT AVG(luot_dang_ky.so_luong) FROM luot_dang_ky JOIN doanh_nghiep ON luot_dang_ky.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Barrio Cafe'
SELECT COUNT(*) FROM doanh_nghiep JOIN khu_vuc_lan_can ON doanh_nghiep.id_doanh_nghiep = khu_vuc_lan_can.id_doanh_nghiep WHERE khu_vuc_lan_can.ten_khu_pho_lan_can = 'Stone Meadows' AND doanh_nghiep.thanh_pho = 'Madison'
SELECT COUNT(*) FROM danh_gia JOIN nguoi_tieu_dung ON danh_gia.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE nguoi_tieu_dung.ten = 'Adrienne'
SELECT COUNT(*) FROM danh_gia JOIN nguoi_tieu_dung ON danh_gia.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE nguoi_tieu_dung.ten = 'Michelle' AND danh_gia.thang = '3' AND danh_gia.nam = 2014
SELECT COUNT(DISTINCT danh_gia.id_doanh_nghiep) FROM danh_gia JOIN nguoi_tieu_dung ON danh_gia.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE nguoi_tieu_dung.ten = 'Michelle' AND danh_gia.nam = 2010
SELECT COUNT(DISTINCT doanh_nghiep.id_doanh_nghiep) FROM doanh_nghiep JOIN danh_gia ON doanh_nghiep.id_doanh_nghiep = danh_gia.id_doanh_nghiep JOIN nguoi_tieu_dung ON danh_gia.id_nguoi_tieu_dung = nguoi_tieu_dung.id_nguoi_tieu_dung WHERE doanh_nghiep.thanh_pho = 'San Diego' AND nguoi_tieu_dung.ten = 'Christine' AND danh_gia.nam = 2010
SELECT COUNT(*) FROM doanh_nghiep WHERE ten = 'Target' AND thanh_pho = 'Los Angeles'
SELECT COUNT(DISTINCT danh_gia.id_nguoi_tieu_dung) FROM danh_gia JOIN doanh_nghiep ON danh_gia.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten LIKE '%quán rượu Ai-len%' AND doanh_nghiep.thanh_pho = 'Dallas'
SELECT AVG(danh_gia_xep_hang) FROM danh_gia WHERE nam = 2014
SELECT COUNT(DISTINCT danh_gia.id_nguoi_tieu_dung) FROM danh_gia JOIN doanh_nghiep ON danh_gia.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.ten = 'Vintner Grill' AND danh_gia.nam = 2010
SELECT COUNT(*) FROM doanh_nghiep JOIN khu_vuc_lan_can ON doanh_nghiep.id_doanh_nghiep = khu_vuc_lan_can.id_doanh_nghiep JOIN danh_gia ON doanh_nghiep.id_doanh_nghiep = danh_gia.id_doanh_nghiep WHERE khu_vuc_lan_can.ten_khu_pho_lan_can = 'South Summerlin'
SELECT COUNT(*) FROM nguoi_tieu_dung WHERE ten = 'Michelle'
SELECT COUNT(*) FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = CAST(loai_hinh.id_doanh_nghiep AS NUMBER) WHERE loai_hinh.ten_loai_hinh = 'nhà hàng'
SELECT COUNT(DISTINCT thanh_pho) FROM doanh_nghiep WHERE ten = 'Panda Express'
SELECT COUNT(*) FROM danh_gia JOIN khoan_tien_boa ON danh_gia.id_nguoi_tieu_dung = khoan_tien_boa.id_nguoi_tieu_dung WHERE khoan_tien_boa.id_nguoi_tieu_dung = (SELECT id_nguoi_tieu_dung FROM nguoi_tieu_dung WHERE ten = 'Michelle')
SELECT SUM(luot_dang_ky.so_luong) FROM doanh_nghiep JOIN khu_vuc_lan_can ON CAST(doanh_nghiep.id_doanh_nghiep AS TEXT) = khu_vuc_lan_can.id_doanh_nghiep JOIN luot_dang_ky ON doanh_nghiep.id_doanh_nghiep = luot_dang_ky.id_doanh_nghiep WHERE khu_vuc_lan_can.ten_khu_pho_lan_can = 'Brighton Heights'
SELECT COUNT(*) FROM danh_gia WHERE thang = '3'
SELECT khoan_tien_boa.thang , COUNT ( * ) FROM khoan_tien_boa JOIN danh_gia ON khoan_tien_boa.id_nguoi_tieu_dung = danh_gia.id_nguoi_tieu_dung GROUP BY khoan_tien_boa.thang
SELECT COUNT(*) FROM khu_vuc_lan_can JOIN doanh_nghiep ON khu_vuc_lan_can.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep WHERE doanh_nghiep.thanh_pho = 'Madison' AND doanh_nghiep.danh_gia_xep_hang = 5
SELECT doanh_nghiep.id_doanh_nghiep, doanh_nghiep.ten, doanh_nghiep.dia_chi_day_du, doanh_nghiep.thanh_pho, doanh_nghiep.vi_do, doanh_nghiep.kinh_do, doanh_nghiep.so_luong_danh_gia, doanh_nghiep.co_mo_cua_hay_khong, doanh_nghiep.danh_gia_xep_hang, doanh_nghiep.tieu_bang FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'Ma-rốc' AND doanh_nghiep.thanh_pho = 'Texas'
SELECT doanh_nghiep.id_doanh_nghiep , doanh_nghiep.ten FROM doanh_nghiep JOIN luot_dang_ky ON doanh_nghiep.id_doanh_nghiep = luot_dang_ky.id_doanh_nghiep GROUP BY doanh_nghiep.id_doanh_nghiep ORDER BY COUNT(luot_dang_ky.so_luong) DESC LIMIT 1
SELECT T1.ten_khu_pho_lan_can FROM khu_vuc_lan_can AS T1 JOIN doanh_nghiep AS T2 ON T1.id_doanh_nghiep = T2.id_doanh_nghiep WHERE T2.thanh_pho = 'Madison' GROUP BY T1.ten_khu_pho_lan_can ORDER BY COUNT(*) DESC LIMIT 1
SELECT T1.id_doanh_nghiep, T1.ten, T1.dia_chi_day_du, T1.thanh_pho, T1.vi_do, T1.kinh_do, T1.so_luong_danh_gia, T1.co_mo_cua_hay_khong, T1.danh_gia_xep_hang, T1.tieu_bang FROM doanh_nghiep AS T1 JOIN loai_hinh AS T2 ON T1.id_doanh_nghiep = T2.id_doanh_nghiep WHERE T2.ten_loai_hinh = 'Mexico' AND T1.thanh_pho = 'Dallas' AND T1.danh_gia_xep_hang >= 3.5
SELECT doanh_nghiep.id_doanh_nghiep, doanh_nghiep.ten, doanh_nghiep.danh_gia_xep_hang, doanh_nghiep.thanh_pho FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'Mexico' AND doanh_nghiep.thanh_pho = 'Dallas' AND doanh_nghiep.danh_gia_xep_hang >= 3.5
SELECT id_doanh_nghiep, ten, dia_chi_day_du, thanh_pho, danh_gia_xep_hang FROM doanh_nghiep WHERE thanh_pho = 'Dallas' AND (ten LIKE '%dịch vụ đỗ xe%' OR (SELECT ten_loai_hinh FROM loai_hinh WHERE loai_hinh.id_doanh_nghiep = doanh_nghiep.id_doanh_nghiep) LIKE '%dịch vụ đỗ xe%')
SELECT T1.ten FROM doanh_nghiep AS T1 JOIN khu_vuc_lan_can AS T2 ON T1.id_doanh_nghiep = T2.id_doanh_nghiep JOIN loai_hinh AS T3 ON T1.id_doanh_nghiep = T3.id_doanh_nghiep WHERE T2.ten_khu_pho_lan_can = 'Meadowood' AND T3.ten_loai_hinh = 'Ý'
SELECT ten FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'bar' AND thanh_pho = 'Los Angeles' AND so_luong_danh_gia >= 30 AND danh_gia_xep_hang > 3
SELECT COUNT(*) FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep WHERE loai_hinh.ten_loai_hinh = 'Nhà hàng Ai Cập' AND doanh_nghiep.thanh_pho = 'Edinburgh'
SELECT T1.id_nguoi_tieu_dung, T1.ten FROM nguoi_tieu_dung AS T1 JOIN danh_gia AS T2 ON T1.id_nguoi_tieu_dung = T2.id_nguoi_tieu_dung GROUP BY T1.id_nguoi_tieu_dung, T1.ten HAVING AVG(T2.danh_gia_xep_hang) < 3
SELECT ten FROM doanh_nghiep JOIN danh_gia ON doanh_nghiep.id_doanh_nghiep = danh_gia.id_doanh_nghiep WHERE danh_gia.thang = '4' GROUP BY doanh_nghiep.id_doanh_nghiep ORDER BY COUNT(*) DESC LIMIT 1
SELECT ten FROM doanh_nghiep JOIN loai_hinh ON doanh_nghiep.id_doanh_nghiep = loai_hinh.id_doanh_nghiep GROUP BY doanh_nghiep.id_doanh_nghiep ORDER BY COUNT(*) DESC LIMIT 1
